displayName=Minimal Boss Health
author=jakebrehm
description=Provides minimal alternatives to the built-in boss health bars
tags=hp,health,bar,boss,fixed
plugins=com.minimalbosshealth.MinimalBossHealth